import enum as e


class CommandIdentifier(e.Enum):
    JOIN = e.auto()
    LEAVE = e.auto()

    CONFIG = e.auto()
    CONFIG_PREFIX = e.auto()
    CONFIG_PREFIX_LIST = e.auto()
    CONFIG_PREFIX_ADD = e.auto()
    CONFIG_PREFIX_REMOVE = e.auto()
    CONFIG_NOWPLAYINGMSG = e.auto()
    CONFIG_NOWPLAYINGMSG_TOGGLE = e.auto()
    CONFIG_RESTRICT = e.auto()
    CONFIG_RESTRICT_LIST = e.auto()
    CONFIG_RESTRICT_ADD = e.auto()
    CONFIG_RESTRICT_REMOVE = e.auto()
    CONFIG_RESTRICT_BLACKLIST = e.auto()
    CONFIG_RESTRICT_WHITELIST = e.auto()
    CONFIG_RESTRICT_CLEAR = e.auto()
    CONFIG_RESTRICT_WIPE = e.auto()

    DEBUG = e.auto()
    DEBUG_MODULE = e.auto()
    DEBUG_MODULE_LOAD = e.auto()
    DEBUG_MODULE_RELOAD = e.auto()
    DEBUG_MODULE_UNLOAD = e.auto()
    DEBUG_COMMAND = e.auto()
    DEBUG_COMMAND_DELETEALL = e.auto()

    NOWPLAYING = e.auto()
    SEARCH = e.auto()
    QUEUE = e.auto()
    LYRICS = e.auto()

    PING = e.auto()
    HELP = e.auto()  # TODO: #27 Implement `/help`

    PLAYPAUSE = e.auto()
    PAUSE = e.auto()
    RESUME = e.auto()
    STOP = e.auto()
    FASTFORWARD = e.auto()
    REWIND = e.auto()
    SKIP = e.auto()
    PLAYAT = e.auto()
    NEXT = e.auto()
    PREVIOUS = e.auto()
    RESTART = e.auto()
    SEEK = e.auto()

    PLAY = e.auto()
    REMOVE = e.auto()
    REMOVE_ONE = e.auto()
    REMOVE_BULK = e.auto()
    CLEAR = e.auto()
    SHUFFLE = e.auto()
    MOVE = e.auto()
    MOVE_LAST = e.auto()
    MOVE_SWAP = e.auto()
    MOVE_INSERT = e.auto()
    REPEAT = e.auto()

    VOLUME = e.auto()
    VOLUME_SET = e.auto()
    VOLUME_UP = e.auto()
    VOLUME_DOWN = e.auto()
    MUTE = e.auto()
    UNMUTE = e.auto()
    MUTEUNMMUTE = e.auto()
    EQUALIZER = e.auto()
    EQUALIZER_PRESET = e.auto()
    EQUALIZER_MANUAL = e.auto()  # TODO: Implement `/equalizer manual`
