#!/bin/bash
# For starting the lavalink server (Linux)

set -a
. ./.env
set +a

(cd lavalink-local && envsubst < application.yml.dev > application.yml && sudo chattr +i application.yml && jdk-13.0.2/bin/java -jar Lavalink.jar)
(cd lavalink-local && sudo chattr -i application.yml && rm application.yml)